services:
  devel:
    build:
      context: .
      dockerfile: Dockerfile.devel
    volumes:
      - ../..:/workspaces
  backend:
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresqldb:5432/${POSTGRES_DB}
    build:
      context: ./backend
      dockerfile: Dockerfile.backend 
    ports:
      - "8000:8000"
    depends_on:
      - postgresqldb
    networks:
      - backend-network
      - frontend-network
  postgresqldb:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - backend-network
    volumes:
      - pgdata:/var/lib/postgresql
      - ./setup/init_script.sql:/docker-entrypoint-initdb.d/init_script.sql:ro

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  pgdata:
    